name: Production Branch Workflow

on:
  push:
    branches:
      - production

jobs:
  verified-commit-check-initial:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check for unverified commits
        uses: nadock/verified_commits_check@v1

  remove-arbitrary-files:
    needs: verified-commit-check-initial
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          token: ${{ secrets.GH_TOKEN }}

      - name: Remove .github folder
        run: rm -rf .github

      - name: Set up git user
        run: |
          git config --local user.email "noreply@gamedevq.com"
          git config --local user.name "GitHub Action"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          trust_level: 5

      - name: Push to production branch
        run: |
          git checkout -B production
          git add .
          COMMIT_MSG="production: $(git log -1 --pretty=%B)"
          git commit --signoff -m "$COMMIT_MSG"
          git push -f origin production

  verified-commit-check-final:
    depends-on: remove-arbitrary-files
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check for unverified commits
        uses: nadock/verified_commits_check@v1
